import "../styles/globals.css"

import { draftMode } from "next/headers"
import { HEADER } from "@/graphql/header"
import { Header } from "@/payload-types"

import { request } from "@/lib/cms"
import { fontHeading, fontMono, fontSans } from "@/lib/fonts"
import { cn } from "@/lib/utils"
import { PreviewBar } from "@/components/preview-bar"
import { SiteHeader } from "@/components/site-header"
import { TailwindIndicator } from "@/components/tailwind-indicator"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const fetchHeader = async () => {
  const { isEnabled } = draftMode()

  const data = await request<{ Header: Header }>({
    collection: "header",
    query: HEADER,
    draft: isEnabled,
  })

  return data
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default async function RootLayout({ children }: RootLayoutProps) {
  const header = await fetchHeader()

  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body
          suppressHydrationWarning={true}
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable,
            fontMono.variable,
            fontHeading.variable
          )}
        >
          <div className="relative mb-96 flex min-h-screen flex-col pb-96">
            <SiteHeader {...header.Header} />
            <main className="flex-1">{children}</main>
          </div>
          <TailwindIndicator />
          <PreviewBar />
        </body>
      </html>
    </>
  )
}
